# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RTX_BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.RTX_BUTTON.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.RTX_BUTTON.setObjectName("RTX_BUTTON")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(20, 30, 113, 20))
        self.input_name.setObjectName("input_name")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_name.setObjectName("label_name")
        self.input_email = QtWidgets.QLineEdit(self.centralwidget)
        self.input_email.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.input_email.setObjectName("input_email")
        self.label_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_name_2.setGeometry(QtCore.QRect(150, 10, 47, 16))
        self.label_name_2.setObjectName("label_name_2")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(280, 30, 113, 20))
        self.input_password.setObjectName("input_password")
        self.label_name_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_name_3.setGeometry(QtCore.QRect(280, 10, 47, 13))
        self.label_name_3.setObjectName("label_name_3")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(110, 90, 75, 23))
        self.submit_button.setObjectName("submit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RTX_BUTTON.setText(_translate("MainWindow", "RTX Button"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_name_2.setText(_translate("MainWindow", "Email"))
        self.label_name_3.setText(_translate("MainWindow", "Password"))
        self.submit_button.setText(_translate("MainWindow", "submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
